name: frontend_app_workflow

on:
    push:
        paths:
            "frontend/**"

jobs:

    frontend_build:

        runs-on: ubuntu-latest

        steps:
            - name: checking out project
              uses: actions/checkout@v3

            - name: configure node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            
            - name: cache node_modules
              uses: actions/cache@v3
              with:
                path: frontend/node_modules
                key: node_modules-${{hashFiles('**/package-lock.json')}}

            - name: Install dependencies
              run: |
                cd frontend
                npm ci
            
            - name: Build and Push to ghcr.io
              run: |
                cd frontend
                npm run build
                docker build -t ghcr.io/${{ secrets.GIT_USERNAME }}/bootcamp_frontend_app:v${{ github.run_number }} .
                docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
                docker push ghcr.io/${{ secrets.GIT_USERNAME }}/bootcamp_frontend_app:v${{ github.run_number }}

            - name: Deploy image to EC2
              run: |
                echo "${{secrets.PRIVATE_KEY}}" > my-first-pem
                chmod 400 my-first-pem
                ssh -o StrictHostKeyChecking=no -i "my-first-pem" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
                    docker stop frontend
                    docker rm frontend
                    docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
                    docker run -d -p 8080:8080 --name=frontend ghcr.io/${{ secrets.GIT_USERNAME }}/bootcamp_frontend_app:v${{ github.run_number }}
                '
                rm my-first-pem
            